name: ecommerce_app
description: "An Ecommerce App "

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  awesome_rating: ^0.0.4
  add_to_cart_animation: ^2.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sidebarx: ^0.16.3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  meta: ^1.10.0
  sqflite: ^2.3.1
  flutter_slidable: ^3.0.1
  lottie: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
